use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{DeriveInput, parse_macro_input};

///
/// # Example
/// ```ignore
/// #[derive(IntoRows)]
/// pub struct MySimpleType(String);
/// ```
///
pub fn handle_derive_into_rows(input: TokenStream) -> TokenStream {
    let ast = parse_macro_input!(input as DeriveInput);
    let ident = &ast.ident;
    let (impl_generics, ty_generics, _where_clause) = ast.generics.split_for_impl();

    let trait_ident = format_ident!("{}IntoRows", ident);

    // Generate documentation
    let doc = format!(
        "Trait for converting collections into rows of `{}`.\n\n\
         This trait is automatically generated by `#[derive(IntoRows)]`.\n\n\
         # Example\n\
``````\n\
         use {}IntoRows;\n\
         // Implementation details...\n\
`````",
        ident, ident
    );

    let expanded = quote! {
        #[doc = #doc]
        pub trait #trait_ident #impl_generics {
            /// An iterator over individual rows
            type RowIter: Iterator<Item = #ident #ty_generics>;
            /// An iterator over collections of rows
            type Rows: Iterator<Item = Self::RowIter>;
            /// Convert this value into an iterator of row iterators
            fn into_rows(self) -> Self::Rows;
        }
    };

    TokenStream::from(expanded)
}
